## Data Plots

Data used here is from [this Kaggle page](https://www.kaggle.com/PromptCloudHQ/world-happiness-report-2019) which has been released by SDSN and extracted by PromptCloud's custom web crawling solution.

In [3]:
data.head(10)

,Country (region),Ladder,SD of Ladder,Positive affect,Negative affect,Social support,Freedom,Corruption,Generosity,Log of GDP per capita,Healthy life expectancy
0,Finland,1,4,41.0,10.0,2.0,5.0,4.0,47.0,22.0,27.0
1,Denmark,2,13,24.0,26.0,4.0,6.0,3.0,22.0,14.0,23.0
2,Norway,3,8,16.0,29.0,3.0,3.0,8.0,11.0,7.0,12.0
3,Iceland,4,9,3.0,3.0,1.0,7.0,45.0,3.0,15.0,13.0
4,Netherlands,5,1,12.0,25.0,15.0,19.0,12.0,7.0,12.0,18.0
5,Switzerland,6,11,44.0,21.0,13.0,11.0,7.0,16.0,8.0,4.0
6,Sweden,7,18,34.0,8.0,25.0,10.0,6.0,17.0,13.0,17.0
7,New Zealand,8,15,22.0,12.0,5.0,8.0,5.0,8.0,26.0,14.0
8,Canada,9,23,18.0,49.0,20.0,9.0,11.0,14.0,19.0,8.0
9,Austria,10,10,64.0,24.0,31.0,26.0,19.0,25.0,16.0,15.0

1. <b>Country (region)</b> Name of the country.
2. <b>Ladder</b> is a measure of life satisfaction.
3. <b>SD of Ladder</b> Standard deviation of the ladder.
4. <b>Positive affect</b> Measure of positive emotion.
5. <b>Negative affect</b> Measure of negative emotion.
6. <b>Social support</b> The extent to which Social support contributed to the calculation of the Happiness Score.
7. <b>Freedom</b> The extent to which Freedom contributed to the calculation of the Happiness Score.
8. <b>Corruption</b> The extent to which Perception of Corruption contributes to Happiness Score.
9. <b>Generosity</b> The extent to which Generosity contributed to the calculation of the Happiness Score.
10. <b>Log of GDP per capita</b> The extent to which GDP contributes to the calculation of the Happiness Score.
11. <b>Healthy life expectancy</b> The extent to which Life expectancy contributed to the calculation of the Happiness Score.

Data is sorted in a way the country on top of the dataframe is the happiest while the last is the opposite.

In [9]:
data.describe()

,Pos,Neg,Social support,Freedom,Corruption,Generosity,GDP,Life expectancy
count,140.000000,140.000000,140.000000,140.000000,140.000000,140.000000,140.000000,140.000000
mean,78.242857,79.157143,77.500000,78.828571,75.700000,78.850000,79.014286,75.478571
std,44.331627,44.506126,45.815787,45.108972,42.656011,44.727782,43.356310,43.979961
min,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,2.000000,1.000000
25%,40.750000,40.750000,36.750000,39.750000,39.750000,40.750000,41.750000,36.750000
50%,78.500000,78.500000,77.500000,79.500000,76.500000,79.500000,78.500000,77.500000
75%,116.250000,117.250000,118.250000,118.250000,112.250000,116.250000,117.250000,113.250000
max,154.000000,154.000000,155.000000,155.000000,148.000000,155.000000,152.000000,150.000000

[Full Report]()

[More Posts in different topics]()